// Do not edit. This file is machine generated by the Resource DLL Wizard.

library CDWav;

{$R *.RES}
{ITE} {LCID:00000409:00000413} {}
{ITE} {DFMFileType} {About.dfm}
{ITE} {DFMFileType} {AboutFull.dfm}
{ITE} {DFMFileType} {AboutShare.dfm}
{ITE} {DFMFileType} {AuditionFrm.dfm}
{ITE} {DFMFileType} {AutoCut.dfm}
{ITE} {DFMFileType} {DAEFrm.dfm}
{ITE} {DFMFileType} {DirNameFrm.dfm}
{ITE} {DFMFileType} {DlgJumpTo.dfm}
{ITE} {DFMFileType} {DlgRecShare.dfm}
{ITE} {DFMFileType} {FileAssociations.dfm}
{ITE} {DFMFileType} {FormatFrm.dfm}
{ITE} {DFMFileType} {MAIN.dfm}
{ITE} {DFMFileType} {Properties.dfm}
{ITE} {DFMFileType} {RecordFrm.dfm}
{ITE} {DFMFileType} {RegisterFrm.dfm}
{ITE} {DFMFileType} {SelectDirFrm.dfm}
{ITE} {DFMFileType} {Settings.dfm}
{ITE} {DFMFileType} {TimeSplitFrm.dfm}
{ITE} {DFMFileType} {WDInfo.dfm}
{ITE} {DFMFileType} {working.dfm}
{ITE} {RCFileType} {CDWav_DRC.rc}

{$R 'About.dfm' AboutBox:TForm}
{$R 'AboutFull.dfm' AboutBoxFull:TForm(AboutBox)}
{$R 'AboutShare.dfm' AboutBoxShare:TForm(AboutBox)}
{$R 'AuditionFrm.dfm' AuditionForm:TForm}
{$R 'AutoCut.dfm' AutoCutDlg:TForm}
{$R 'DAEFrm.dfm' DAEForm:TForm}
{$R 'DirNameFrm.dfm' DirNameForm:TForm}
{$R 'DlgJumpTo.dfm' JumpToDlg:TForm}
{$R 'DlgRecShare.dfm' DlgRecordShare:TForm(DlgRecord)}
{$R 'FileAssociations.dfm' FileAssociationDlg:TForm}
{$R 'FormatFrm.dfm' FormatForm:TForm}
{$R 'MAIN.dfm' MainForm:TForm}
{$R 'Properties.dfm' FilePropertiesForm:TForm}
{$R 'RecordFrm.dfm' DlgRecord:TForm(FormatForm)}
{$R 'RegisterFrm.dfm' RegisterForm:TForm}
{$R 'SelectDirFrm.dfm' SelectDirDlg:TForm(FormatForm)}
{$R 'Settings.dfm' SettingsDialog:TForm}
{$R 'TimeSplitFrm.dfm' TimeSplitForm:TForm}
{$R 'WDInfo.dfm' WaveInfoForm:TForm}
{$R 'working.dfm' LoadingDlg:TForm}
{$R 'CDWav_DRC.res' 'CDWav_DRC.rc'}

{$E NLD}

begin
end.